#!/bin/bash
clear
grenbo="\e[92;1m"
NC='\033[0m'
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│$NC\033[42m          MENU MANAGER SS                 $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│  ${grenbo}1.${NC} \033[0;36mCreating a ss Account${NC}"
echo -e "\033[1;93m│  ${grenbo}2.${NC} \033[0;36mTrial a ss Account${NC}"
echo -e "\033[1;93m│  ${grenbo}3.${NC} \033[0;36mDelete ss Account${NC}"
echo -e "\033[1;93m│  ${grenbo}4.${NC} \033[0;36mRenew ss Account${NC}"
echo -e "\033[1;93m│  ${grenbo}5.${NC} \033[0;36mCheck ss login Account${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 4 ] : " menu
case $menu in
1)
    add-ss
    ;;
2)
    trial-ss
    ;;
3)
    del-ss
    ;;
4)
    renew-ss
    ;;
5)
    cek-ss
    ;;
*)
    menu
    ;;
esac
