#!/bin/bash
clear
grenbo="\e[92;1m"
NC='\033[0m'
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " \e[1;97;101m            MENU MANAGER SSH            \E[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;93m〔⎆〕 ${grenbo}1.${NC} \033[0;36mCreating SSH OVPN Account${NC}"
echo -e "\033[1;93m〔⎆〕 ${grenbo}2.${NC} \033[0;36mTrial SSH OVPN Account${NC}"
echo -e "\033[1;93m〔⎆〕 ${grenbo}3.${NC} \033[0;36mDelete SSH OVPN Account${NC}"
echo -e "\033[1;93m〔⎆〕 ${grenbo}4.${NC} \033[0;36mRenew SSH OVPN Account${NC}"
echo -e "\033[1;93m〔⎆〕 ${grenbo}5.${NC} \033[0;36mCheck SSH OVPN login Account${NC}"
echo -e "\033[1;93m〔⎆〕 ${grenbo}6.${NC} \033[0;36mList ACCOUNT SSH Ovpn${NC}"
echo -e "\033[1;93m〔⎆〕 ${grenbo}7.${NC} \033[0;36mKill ACCOUNT SSH Ovpn${NC}"
echo -e "\033[1;93m〔⎆〕 ${grenbo}8.${NC} \033[0;36mCek LOG ACCOUNT SSH Ovpn${NC}"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 4 ] : " menu
case $menu in
1)
    add-ssh
    ;;
2)
    triall-ssh
    ;;
3)
    del-ssh
    ;;
4)
    renew-ssh
    ;;
5)
    cek-ssh
    ;;
6)
    member
    ;;
7)
    autokill
    ;;
8)
    user-ssh
    ;;
*)
    menu
    ;;
esac

