#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
GARIS="\033[1;36m"
NC="\033[0m"
IPVPS=$(curl -s ipv4.icanhazip.com);
PUB=$(cat /etc/slowdns/server.pub)
NS=$(cat /etc/xray/dns)
echo "PROJECT"
clear
if [[ "$IP2" = "" ]]; then
domain=$(cat /etc/xray/domain)
else
domain=$IP2
fi
IP=$(wget -qO- icanhazip.com);
"$(cat ~/log-install.txt | grep -w "Stunnel4" | cut -d: -f2)"
"$(cat ~/log-install.txt | grep -w "Squid" | cut -d: -f2)"
"$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
"$(netstat -nlpu | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
Login=Trial-SSH`</dev/urandom tr -dc X-Z0-9 | head -c4`
hari="1"
Pass=1
echo Ping Host
echo Cek Hak Akses...
sleep 0.5
echo Permission Accepted
clear
sleep 0.5
echo Membuat Akun: $Login
sleep 0.5
echo Setting Password: $Pass
sleep 0.5
clear
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
created=`date -d "0 days" +"%d-%m-%Y"`
CITY=$(cat /etc/xray/city)
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^#ssh#" | grep -w "${Login}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${Login}\b/d" /etc/ssh/.ssh.db
fi
echo "#ssh# ${Login} " >>/etc/ssh/.ssh.db
clear
echo -e "${GARIS}◇━━━━ Account Info ━━━━◇${NC}"
echo -e "Username	: $Login"
echo -e "Password	: $Pass"
echo -e "Expired         : $(date +%d/%m/%y -d "$exp")"
echo -e "${GARIS}◇━━━━━━━━━━━━━━━━━◇${NC}"
echo -e "Host CF         : $domain"
echo -e "IP              : $IP"
echo -e "ISP		: $CITY"
echo -e "Host Bug	: bug.$domain"
echo -e "Note: bug bisa di ganti bebas"
echo -e "${GARIS}◇━━━━━━ Non TLS ━━━━━◇${NC}"
echo -e "OpenSSH         :143,80,22"
echo -e "Dropbear	:443,109"
echo -e "WS Dropbear	:80,143"
echo -e "${GARIS}◇━━━━━ SSL / TLS ━━━━━◇${NC}"
echo -e "OpenSSH         :443,22"
echo -e "Dropbear	:143,777"
echo -e "Ws Dropbear	:443"
echo -e "${GARIS}◇━━━━ Mode Proxy ━━━━━◇${NC}"
echo -e "OHP OpenSSH	:8080"
echo -e "OHP Dropbear	:8181"
echo -e "Squid     	:3128"
echo -e "Socks5	        :1080"
echo -e "${GARIS}◇━━━━━ Slow DNS ━━━━━◇${NC}"
echo -e "NS SlowDNS      : $NS"
echo -e "Port SlowDNS    :22 / Bebas"
echo -e "Pubkey SlowDNS  : $PUB"
echo -e "${GARIS}◇━━━━━ OpenVPN ━━━━━◇${NC}"
echo -e "OpenVPN WS SSL  : https://$domain:81/"$domain"-ws-ssl.ovpn"
echo -e "OpenVPN SSL     : https://$domain:81/"$domain"-ssl.ovpn"
echo -e "OpenVPN TCP     : https://$domain:81/"$domain"-tcp.ovpn"
echo -e "OpenVPN UDP     : https://$domain:81/"$domain"-udp.ovpn"
echo -e "${GARIS}◇━━━━━━━━━━━━━━━━━◇${NC}"
echo -e "UDPcustom	:54-65535"
echo -e "BadVPN/UDPGW	:7200,7300"
echo -e "Reboot VPS	: 00.00 (GMT+7)"
echo -e "${GARIS}◇━━━━━━━━━━━━━━━━━◇${NC}"
echo -e "GET / HTTP/1.1[crlf]Host: [host][crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"
echo -e "${GARIS}◇━━━━━━━━━━━━━━━━━◇${NC}"
echo -e ""
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
ssh
